apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: dp
  ports:
    - port: 8080 # service port
      targetPort: 80 # pod/container port
      
      